# 프로미스

## 비동기 처리를 위한 콜백 패턴의 단점

1. 콜백 헬

   ajax요청을 위한 함수는 다 비동기 함수로 함수 내부에서 응답값을 받아 실행하는 코드를 넣지 않고 외부에서 넣으면 예상대로 동작하지 않는다. 

   **서버의 응답 결과에 대한 후속 처리를 위해 콜백 함수를 비동기 함수인 get에 전달해야 한다.**

   그렇기 때문에 ajax요청의 인수로 넣어주는 콜백함수에 응답 이후의 할일을 주게 된다. 이때 할 일이 많아지면 그만큼 콜백함수도 커지고 길어진다.

2. 에러처리의 한계

   비동기 처리의 콜백 문제중 가장 큰 문제는 에러 처리이다.

   ```
   try {
     setTimeout(() => { throw new Error('Error!'); }, 1000);
   } catch (e) {
     // 에러를 캐치하지 못한다
     console.error('캐치한 에러', e);
   }
   ```

   try문에서 부른 setTimeOut은 1초뒤에 에러를 발생시키지만 catch문이 그 에러를 잡지 못한다. 비동기 함수인 setTImeOut이 호출되면 그 실행 컨텍스트가 생성되어 콜 스택에 푸쉬되고 비동기 함수임으로 함수의 호출을 기다리지 않고 즉시 종료되어 콜스택에서 팝된다. 이후 브라우저의 타이머가 만료되면 setTimeOut함수의 콜백이 테스크 큐로 푸쉬되고 콜스택에 모두 비어졌을때 이벤트 루프에 의해서 콜스택으로 푸쉬된다.

   이때 setTimeout 함수는 이미 호출 스택에서 제거된 상태이다. 이것은 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다라는 것을 의미한다. setTimeout 함수의 콜백 함수의 호출자(caller)가 setTimeout 함수라면 콜 스택의 현재 실행중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때, 현재 실행중인 실행 컨텍스트의 하위 실행 컨텍스트가 setTimeout 함수이어야 한다.

   에러는 호출자(caller) 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트에서 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 하지만 위에서 살펴본 바와 같이 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다. 따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

## 프로미스의 생성

프로미스는 promise 생성자함수를 통해서 인스턴스화 한다. 이 생성자함수는 비동기 처리를 수행할 콜백 함수를 인자로 받는데 이 함수는 resolve와 reject함수를 인수로 받는다.

```
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

promise생성자 함수가 인수로 전달받은 콜백함수 내부에서 비동기 처리를 수행한다. 이때 비동기 처리의 성공 여부에 따라 res혹은 rej를 호출한다.

```
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};


// promiseGet는 Promise 객체를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```

프로미스로 구현된 비동기 함수는 Promise 객체를 반환한다. 반환된 Promise 객체는 비동기 처리가 성공(fulfilled)했는지 또는 실패(rejected)했는지 등의 상태(state) 정보를 갖는다.

| 상태          | 의미                                                         | 구현                                               |
| :------------ | :----------------------------------------------------------- | :------------------------------------------------- |
| pending       | 비동기 처리가 아직 수행되지 않은 상태                        | resolve 또는 reject 함수가 아직 호출되지 않은 상태 |
| **fulfilled** | 비동기 처리가 수행된 상태 (성공)                             | resolve 함수가 호출된 상태                         |
| **rejected**  | 비동기 처리가 수행된 상태 (실패)                             | reject 함수가 호출된 상태                          |
| settled       | fulfilled 또는rejected와 상관 없이 pending 이 아닌 상태, 즉 비동기 처리가 수행된 상태 | resolve 또는 reject 함수가 호출된 상태             |

Promise 객체의 상태 정보는 resolve 또는 reject 함수를 호출하는 것으로 결정된다. resolve 또는 reject 함수를 호출할 때 전달한 비동기 처리 결과 또는 에러는 Promise 객체의 후속 처리 메서드에게 전달된다.

## 프로미스 후속처리 메소드

프로미스로 구현된 비동기 함수는 promise객체를 반환해야한다. 프로미스로 구현된 비동기 함수를 호출하는 면에서는 promise객체의 후속처리 메소드를 통해서 비동기의 처리 결과를 받아 후속 처리를 한다.

Promise.prototype.then

then 메서드는 두 개의 콜백 함수를 인수로 전달 받는다. 첫 번째 콜백 함수는 프로미스가 fulfilled 상태(resolve 함수가 호출된 상태)일 때 호출되고, 두 번째 콜백 함수는 프로미스가 rejected 상태(reject 함수가 호출된 상태)일 때 호출된다. then 메서드는 언제나 Promise 객체를 반환한다. then 메서드의 콜백 함수가 Promise 객체가 아닌 값을 반환하면 그 값을 resolve 또는 reject 하여 Promise 객체를 반환한다.

```
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

Promise.prototype.catch

catch 메서드는 한 개의 콜백 함수를 인수로 전달 받는다. catch 메서드의 콜백 함수는 예외(비동기 처리에서 발생한 에러와 then 메서드에서 발생한 에러)가 발생하면 호출된다. catch 메서드는then(undefined, onRejected)과 동일하게 동작한다. 따라서 then 메서드와 마찬가지로 언제나 Promise 객체를 반환한다.

```
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)); // Error: rejected
```

- Promise.prototype.finally

finally 메서드는 한 개의 콜백 함수를 인수로 전달 받는다. finally 메서드의 콜백 함수는 프로미스의 성공(fulfilled) 또는 실패(rejected)와 상관없이 무조건 한 번 호출된다. **finally 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야할 처리해야할 때 유용**하다. finally 메서드도 then/catch 메서드와 마찬가지로 언제나 Promise 객체를 반환한다. finally 메서드는 2020년 5월 현재, TC39 프로세스의 stage 4에 제안되어 있다. IE를 제외한 대부분의 브라우저에서 지원하고 있다.

```
new Promise(() => {})
  .finally(() => console.log('finally')); // finally
```

## 프로미스 에러처리

프로미스 객체에서 비동기 처리 결과에 대한 후속 처리는 then,catch,finally등의 메소들 사용해서 처리한다. 에러는 then메소드에서 처리가 가능하다.

```
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res), err => console.error(err)); // Error: 404
```

then 뿐 아니라 catch를 사용해서 잡을 수도 있다.

```
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)); // Error: 404
```

catch 메서드는 에러를 처리한다는 점에서 then 메서드의 두 번째 콜백 함수와 동일하지만 미묘한 차이가 있다. then 메서드의 두 번째 콜백 함수는 비동기 처리에서 발생한 에러(reject 함수가 호출된 상태)만을 캐치한다. 즉, then 메서드 내부의 에러를 캐치하지 못한다. 하지만 catch는 then 매서드 내부의 에러도 잡아낸다.

## 프로미스 체이닝

비동기 함수의 처리결과를 가지고 다른비동기 함수를 호출해야 하는 경우, 비동기 함수의 중첩이 되어 콜백헬이 발생한다. promise객체를 반환한 비동기 함수는 프로미스 후속처리 메서드인 then, catch, finally메소드를 사용할 수 있다. 이 메소드들은 promise 객체를 반환하기 떄문에 후속 처리 메서드를 체이닝해서 호출하는 방식으로 콜백 헬을 해결할 수 있다.

```
const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then(userInfo => console.log(userInfo))
  .catch(err => console.error(err));
```

## promise의 정적 메소드

프로미스도 생성자함수처럼 사용되어도 결국 객체이므로 메소드를 갖는다.

1. promise. resolve, reject

   이미 존재하는 값을 래핑하여 promise 객체를 생성하기 위해서 사용한다. promise.resolve는 인자로 전달된 값을 resolve하는 promise객체를 생성한다. promise.reject는 인자로 전달된 값을 reject하는 promise객체를 생성한다.

2. promise.all

   이 메소드는 promise 객체를 요소로 갖는 배열 등의 이터러블을 인자로 받는다. 그리고 전달받은 객체들을 모두 연속적으로 처리하고 그 결과를 res하는 새로운 프로미스를 반환한다.

   ```
   Promise.all([
     new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
     new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
     new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
   ]).then(console.log) // [ 1, 2, 3 ]
     .catch(console.error);
   ```

   이 예제를 보면 시간순으로는 321이 맞지만 promise.all은 인자들을 연속적으로 실행한다. 그리고 그 결과를 뱅ㄹ에 담아 resolve하는 새로운 promise객체를 반환한다. 이때 객체의 처리가 하나라도 실패하면 가장 먼저 실패한 객체의 rej를 rej해주는 promise객체를 즉시 반환한다. 성공과는 달리 실패하는 순간 반환한다.

3. promise.race

   promise.race는 promise.all과 비슷하게 promise 객체 여러개를 인수로 받지만 all과는 다르게 가장 먼저 res혹은 rej한 promise 객체를 반환한다.

4. promise.allSettled

   이 메소드는 위의 두 메소드와 같이 promise를 담은 배열 등의  이터러블을 인자로 받아서 그 promise객체들을 연속적으로 처리하고 결과를 배열로 반환한다.  이때 통신 결과와는 상관없이 모두 반환한다. 성공한 통신의 결과 객체에는 결과 상태인 status와 통신결과물인 value를, 실패한 경우 실패 상태를 나타내는 status와 실패 이유를 알려주는 reason을 반환한다.